SklepInternetowy_v_3/Models/Product/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SklepInternetowy_v_3.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }

        [Required]
        [MinLength(6)]
        [MaxLength(50)]
        public string ProductName { get; set; }

        [Required]
        public int? CategoryId { get; set; }

        public string ProductDescription { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [Required]
        public int ProductAmount { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Photos> ProductPhotos { get; set; }
        public virtual ICollection<CartItem> Items { get; set; }
    }
}

SklepInternetowy_v_3/Models/Product/ProductClientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SklepInternetowy_v_3.Models
{
    public class ProductClientViewModel
    {
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        public decimal Price { get; set; }

        public string ProductPhoto { get; set; }
    }
}

SklepInternetowy_v_3/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SklepInternetowy_v_3.Models;
using AutoMapper;
using SklepInternetowy_v_3.Helpers;

namespace SklepInternetowy_v_3.Controllers
{
    [AuthorizeRole(Roles = AppConstants.AdminRole)]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        [AllowAnonymous]
        public ActionResult Category(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            List<Product> products = db.Products.Where(p => p.ProductAmount > 0 && p.ProductCategory.CategoryName.Equals(id, StringComparison.InvariantCulture))
                .Include(p => p.ProductCategory).Include(p => p.ProductPhotos).ToList();
            var productsView = Mapper.Map<List<Product>, List<ProductClientViewModel>>(products);
            var category = db.ProductCategories.SingleOrDefault(c => c.CategoryName.Equals(id, StringComparison.InvariantCulture));
            ViewBag.CategoryName = category != null ? category.CategoryName : "Kategoria nieznana";
            return View("UserProductList", productsView);
        }

        // GET: Products
        [AllowAnonymous]
        public ActionResult Index(int? id)
        {
            if (User.IsInRole(AppConstants.AdminRole))
            {
                List<Product> products = db.Products.Where(p => p.ProductAmount > 0).Include(p => p.ProductCategory).Include(p => p.ProductPhotos).ToList();
                var productsView = Mapper.Map<List<Product>, List<ProductViewModel>>(products);
                return View(productsView);
            }
            else
            {
                List<Product> products = db.Products.Where(p => p.ProductAmount > 0 && p.CategoryId == id).Include(p => p.ProductCategory).Include(p => p.ProductPhotos).ToList();
                var productsView = Mapper.Map<List<Product>, List<ProductClientViewModel>>(products);
                var category = db.ProductCategories.SingleOrDefault(c => c.CategoryId == id);
                ViewBag.CategoryName = category != null ? category.CategoryName : "Kategoria nieznana";
                return View("UserProductList", productsView);
            }
        }


        // GET: Products/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include(p => p.ProductPhotos).SingleOrDefault(p => p.ProductId == id && p.ProductAmount > 0);
            if (product == null)
            {
                return HttpNotFound();
            }
            var productView = Mapper.Map<Product, ProductViewModel>(product);
            return View(productView);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            InitCategoriesList();
            return View();
        }

        private void InitCategoriesList(int? selectedValue = null)
        {
            var categories = db.ProductCategories.Where(c => c.ParentCategoryId != null);
            ViewBag.CategoryId = new SelectList(categories, "CategoryId", "CategoryName", selectedValue);
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel productViewModel, IEnumerable<HttpPostedFileBase> upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.Any(u => u != null && u.ContentLength > 0))
                {
                    string validationError = validatePhotoUpload(upload);
                    if (validationError != null)
                    {
                        ModelState.AddModelError("ProductPhotos", validationError);
                        ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", productViewModel.CategoryId);
                        return View(productViewModel);
                    }
                    Product product = new Product()
                    {
                        ProductName = productViewModel.ProductName,
                        ProductDescription = productViewModel.ProductDescription,
                        Price = productViewModel.Price,
                        ProductAmount = productViewModel.ProductAmount,
                        CategoryId = productViewModel.CategoryId
                    };
                    product.ProductPhotos = new List<Photos>();
                    foreach (HttpPostedFileBase photo in upload)
                    {
                        string photoNameWithTimeStamp = AppendTimeStamp(photo.FileName);
                        string path = Path.Combine(Server.MapPath("~/Images"), photoNameWithTimeStamp);
                        photo.SaveAs(path);
                        product.ProductPhotos.Add(new Photos(photoNameWithTimeStamp));
                    }
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("ProductPhotos", "Produkt musi zawierać co najmniej jedno zdjęcie");
            }
            InitCategoriesList(productViewModel.CategoryId);
            return View(productViewModel);
        }

        private string validatePhotoUpload(IEnumerable<HttpPostedFileBase> upload)
        {
            if (upload.Count() > 5)
            {
                return "Nie można dodać więcej niż 5 zdjęć";
            }
            foreach (HttpPostedFileBase photo in upload)
            {
                if (photo.ContentLength > 6500000)
                {
                    return "Zdjęcie nie może być większe niż 6MB";
                }
            }
            return null;
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include(p => p.ProductPhotos).SingleOrDefault(p => p.ProductId == id && p.ProductAmount > 0);
            if (product == null)
            {
                return HttpNotFound();
            }
            InitCategoriesList(product.CategoryId);
            var productView = Mapper.Map<Product, ProductViewModel>(product);
            return View(productView);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel productView, IEnumerable<HttpPostedFileBase> upload)
        {
            if (ModelState.IsValid)
            {
                Product product = db.Products.Include(p => p.ProductPhotos).SingleOrDefault(p => p.ProductId == productView.ProductId && p.ProductAmount > 0);
                if (product == null)
                {
                    return HttpNotFound();
                }
                if (upload != null && upload.Any(u => u != null && u.ContentLength > 0))
                {
                    string validationError = validatePhotoUpload(upload);
                    if (validationError != null)
                    {
                        ModelState.AddModelError("ProductPhotos", validationError);
                        ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", productView.CategoryId);
                        return View(productView);
                    }
                    DeleteAllPhotosFromFolder(product);
                    foreach (var photo in product.ProductPhotos.ToList())
                    {
                        db.Entry(photo).State = EntityState.Deleted;
                    }
                    db.SaveChanges();
                    product.ProductPhotos = new List<Photos>();
                    foreach (HttpPostedFileBase photo in upload)
                    {
                        string photoNameWithTimeStamp = AppendTimeStamp(photo.FileName);
                        string path = Path.Combine(Server.MapPath("~/Images"), photoNameWithTimeStamp);
                        photo.SaveAs(path);
                        product.ProductPhotos.Add(new Photos(photoNameWithTimeStamp));
                    }
                }
                product.Price = productView.Price;
                product.ProductName = productView.ProductName;
                product.ProductDescription = productView.ProductDescription;
                product.ProductAmount = productView.ProductAmount;
                product.CategoryId = productView.CategoryId;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", productView.CategoryId);
            return View(productView);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.SingleOrDefault(p => p.ProductId == id && p.ProductAmount > 0);
            if (product == null)
            {
                return HttpNotFound();
            }
            var productView = Mapper.Map<Product, ProductViewModel>(product);
            return View(productView);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

SklepInternetowy_v_3/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SklepInternetowy_v_3.Models;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SklepInternetowy_v_3.Helpers;

namespace SklepInternetowy_v_3.Controllers
{
    [DenyRole(Roles = AppConstants.AdminRole)]
    public class ShoppingCartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ShoppingCart/Cart
        public ActionResult Cart()
        {
            string userId = User.Identity.GetUserId();
            ShoppingCart shoppingCart = db.ShoppingCarts.SingleOrDefault(c => c.CartId == userId);
            if (shoppingCart == null)
            {
                return HttpNotFound("Cannot find cart for user: " + User.Identity.Name);
            }
            ShoppingCartViewModel shoppingCartView = Mapper.Map<ShoppingCart, ShoppingCartViewModel>(shoppingCart);
            return View(shoppingCartView);
        }

        // POST: ShoppingCart/Cart
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SuppressMessage("ReSharper", "RedundantIfElseBlock")]
        public ActionResult Cart(ShoppingCartViewModel shoppingCartViewModel)
        {
            if (ModelState.IsValid)
            {
                ShoppingCart shoppingCart = db.ShoppingCarts.SingleOrDefault(c => c.CartId == shoppingCartViewModel.CartId);
                if (shoppingCart.Items.Any())
                {
                    for (int k = 0; k < shoppingCart.Items.Count; k++)
                    {
                        CartItem item = shoppingCart.Items.ElementAt(k);

                        item.Quantity = shoppingCartViewModel.Items.SingleOrDefault(i => i.ItemId == item.ItemId).Quantity;
                        Product product = db.Products.SingleOrDefault(i => i.ProductId == item.ProductId && i.ProductAmount > 0);
                        if (product == null)
                        {
                            ModelState.AddModelError($"Items[{k}].Quantity", $"Produkt {item.Product.ProductName} nie jest już dostępny.");
                            shoppingCart.Items.Remove(item);
                            db.Entry(item).State = EntityState.Deleted;
                            db.SaveChanges();
                            return View(shoppingCartViewModel);
                        }
                        int productAmount = product.ProductAmount;
                        if (item.Quantity > productAmount)
                        {
                            ModelState.AddModelError($"Items[{k}].Quantity", $"Posiadamy tylko {productAmount} sztuk produktu.");
                            return View(shoppingCartViewModel);
                        }
                    }
                    if (Request.Form["shopping"] != null)
                    {
                        db.SaveChanges();
                        return RedirectToAction("Index", "Home");
                    }
                    else if (Request.Form["order"] != null)
                    {
                        db.SaveChanges();
                        return RedirectToAction("Order", "Order");
                    }
                }
            }
            return View(shoppingCartViewModel);
        }

        // GET: ShoppingCart/AddProduct/5
        [HttpPost]
        public JsonResult AddProduct(int? id)
        {
            if (id == null)
            {
                return Json(new {status ="Error", message = "Nie podano produktu do dodania" });
            }
            Product product = db.Products.Include(p => p.ProductPhotos).SingleOrDefault(p => p.ProductId == id && p.ProductAmount > 0);
            if (product == null)
            {
                return Json(new { status = "Error", message = "Niestety produkt został już wyprzedany" });
            }
            string userId = User.Identity.GetUserId();
            ShoppingCart shoppingCart = db.ShoppingCarts.SingleOrDefault(c => c.CartId == userId);
            if (shoppingCart == null)
            {
                return Json(new { status = "Error", message = "Nie znaleziono koszyka" });
            }
            if (shoppingCart.Items == null)
            {
                shoppingCart.Items = new List<CartItem>();
            }
            if (shoppingCart.Items.Any(i => i.ProductId == id))
            {
                if (shoppingCart.Items.Single(i => i.ProductId == id).Quantity >= product.ProductAmount)
                {
                    return Json(new { status = "Error", message = "Brak wystarczającej ilości produktu" });
                }
                shoppingCart.Items.Single(i => i.ProductId == id).Quantity++;
            }
            else
            {
                CartItem item = new CartItem(product.ProductId, shoppingCart.CartId, 1);
                shoppingCart.Items.Add(item);
            }
            db.SaveChanges();
            return Json(new { status = "Success", message = "Produkt dodany do koszyka" });
        }

        //GET: ShoppingCart/DeleteProduct/5
        public ActionResult DeleteItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem item = db.CartItems.SingleOrDefault(i => i.ItemId == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            db.Entry(item).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Cart");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SklepInternetowy_v_3/Views/Products/Create.cshtml
@model SklepInternetowy_v_3.Models.ProductViewModel

@{
    ViewBag.Title = "Dodaj produkt";
}

<h2>Produkt</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dodaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Cena w PLN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductAmount, new { htmlAttributes = new { @class = "form-control", min = "1" } })
                @Html.ValidationMessageFor(model => model.ProductAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dodaj zdjęcia", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" accept=".jpg,.png" multiple/>
                @Html.ValidationMessageFor(m => m.ProductPhotos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj produkt" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

<script>
    $(document).ready(function() {
        $.validator.methods.number = function(value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SklepInternetowy_v_3/Views/Products/Details.cshtml
@using SklepInternetowy_v_3.Helpers
@using SklepInternetowy_v_3.Models
@model SklepInternetowy_v_3.Models.ProductViewModel
<link href="@Url.Content("~/Content/UserView.css")" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = Model.ProductName;
}

<div class="main container">
    <div id="product-container">
        <div id="product-form-container">
            <div id="product-form-center">
                <div>
                    <div id="product-images">
                        <div id="product-image-tiles">
                            @if (Model.ProductPhotos != null && Model.ProductPhotos.Any())
                            {
                                foreach (string photo in Model.ProductPhotos)
                                {
                                    <div class="image">
                                        @{string path = @Url.Content("~/images/") + photo;}
                                        @Html.Image(path, "Brak zdjęcia", "photos-in-details")
                                    </div>
                                }
                            }
                            else
                            {
                                @:<p> Brak zdjęć </p>
                            }
                        </div>
                        <div id="product-preview">
                            <img id="product-preview-img" src="~/Content/Images/waiting.png" alt=""/>
                        </div>
                    </div>
                </div>
            </div>
            <div id="product-form-right">
                    <div class="product-name">
                        @Html.DisplayFor(model => model.ProductName)
                    </div>
                    <hr/>
                    <div class="product-price">
                        @Html.DisplayFor(model => model.Price) PLN
                    </div>
                    <hr/>
                    <div class="product-description">
                        @Html.DisplayFor(model => model.ProductDescription)
                    </div>
                    
                    <div>
                        @{
                            string addProductAction = Request.IsAuthenticated ? (!User.IsInRole(AppConstants.AdminRole) ? $"addProduct({Model.ProductId})" : "") : "showLoginRequired()";
                        }
                        <button onclick="@addProductAction" class="btn btn-info @(@User.IsInRole(AppConstants.AdminRole) ? "disabled" : "")" id="add-product-button">
                            <span class="glyphicon glyphicon-shopping-cart"></span> DODAJ DO KOSZYKA
                        </button>
                    </div>
                <div id="product-return-list">
                    <a href="@Url.Action("Index", "Products", new { id = Model.CategoryId})">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        Wróć do listy produktów
                    </a>
                </div>
                <hr/>
                <p class="benefits"> <span class="glyphicon glyphicon-home benefit-icons"></span> Darmowa dostawa dla zamówień powyżej 150 PLN</p>
                <p class="benefits"> <span class="glyphicon glyphicon-calendar benefit-icons"></span> 30 dni na zwrot</p>
                <p class="benefits"> <span class="glyphicon glyphicon-gift benefit-icons"></span> Podaruj jako prezent</p>
            </div>
        </div>
    </div>



</div>

<!-- Modal -->
<div class="modal fade" id="add-product-modal" role="dialog">
    <div class="modal-dialog modal-sm">
        <!-- Modal content-->
        <div class="modal-content">
            <div id="add-product-modal-body" class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Zamknij</button>
            </div>
        </div>

    </div>
</div>

<script>

    $(document).ready(function () {
        $("img.photos-in-details").click(function () {
            changePreviewImage($(this));
        });

        setFirstImage();
    });

    function setFirstImage() {
        changePreviewImage($(".photos-in-details:first"));
    }

    function changePreviewImage(selector) {
        var src = selector.attr("src");
        var target = $("#product-preview-img");
        if (target.attr("src") === src) {
            return false;
        }
        target.fadeTo(300, 0.50, function() {
            $(this).attr("src", src);
        }).fadeTo(200, 1);
    }

    function addProduct(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("AddProduct", "ShoppingCart")',
            data: '{ id: "' + id + '" }',
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                $("#add-product-modal-body").html(response["message"]);
                $("#add-product-modal").modal('toggle');
            },
            error: function(res, status, err) {
                alert(err);
            }
        });
    }

    function showLoginRequired() {
        $("#add-product-modal-body").html("Zaloguj się, aby móc dodać produkt do koszyka");
        $("#add-product-modal").modal('toggle');        
    }
</script>

SklepInternetowy_v_3/Views/Products/Edit.cshtml
@model SklepInternetowy_v_3.Models.ProductViewModel

@{
    ViewBag.Title = "Edytuj produkt";
}

<h2>Produkt</h2>


@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edytuj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductAmount, new { htmlAttributes = new { @class = "form-control", min = "1" } })
                @Html.ValidationMessageFor(model => model.ProductAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dodaj nowe zdjęcia", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" accept=".jpg,.png" multiple />
                @Html.ValidationMessageFor(m => m.ProductPhotos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

<script>
    $(document).ready(function() {
        $.validator.methods.number = function(value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SklepInternetowy_v_3/Views/Products/UserProductList.cshtml
@using SklepInternetowy_v_3.Models
@model IEnumerable<SklepInternetowy_v_3.Models.ProductClientViewModel>
<link href="@Url.Content("~/Content/UserView.css")" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Lista produktów";
}

<h2>@ViewBag.CategoryName</h2>
<hr />

<div class="products-wrapper">
    @foreach (var item in Model)
    {
        <div class="product-wrapper">
            @if (item.ProductPhoto.Any())
                {
                <a href="@Url.Action("Details", "Products", new {id = item.ProductId})">
                    <img src="@Url.Content("~/Images/" + item.ProductPhoto)" alt="Brak zdjęcia" class="product-photo-on-list"/>
                </a>
            }

            <div class="product-name-on-list">
                @Html.ActionLink(item.ProductName, "Details", "Products", new { id = item.ProductId }, htmlAttributes: new { @class = "product-view-link" })
            </div>
            <div>
                @Html.DisplayFor(modelItem => item.Price) PLN
            </div>
        </div>
    }
</div>