SklepInternetowy_v_3/Controllers/HeaderActionsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using SklepInternetowy_v_3.Helpers;
using SklepInternetowy_v_3.Models;
using SklepInternetowy_v_3.Models.AdminItems;
using SklepInternetowy_v_3.Models.Category;

namespace SklepInternetowy_v_3.Controllers
{
    public class HeaderActionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Categories()
        {
            var productCategories = db.ProductCategories.Where(c => c.ParentCategoryId == null).Include(c => c.SubCategories).ToList();
            var categoryViews = AutoMapper.Mapper.Map<List<ProductCategory>, List<CategoryHeaderItemViewModel>>(productCategories);

            return PartialView("_CategoriesHeaderPartial", categoryViews);
        }


        [AuthorizeRole(Roles = AppConstants.AdminRole)]
        public ActionResult Orders()
        {
            var orders = db.Orders.OrderByDescending(o => o.OrderDate).Include(o => o.User).Include(o => o.ItemsInOrder).ToList();
            var userOrders = orders.GroupBy(o => o.User.UserName, o => o, (key, order) => new UserOrdersViewModel()
            {
                UserName = key,
                SubmittedOrders = AutoMapper.Mapper.Map<List<Order>,List<SubmittedOrderViewModel>>(order.ToList())
            });
            return View(userOrders);
        }

        [AuthorizeRole(Roles = AppConstants.AdminRole)]
        public ActionResult Users()
        {
            var users = db.Users.ToList();
            var usersNames = users.Select(u => new UserDetailsViewModel(u.UserName, u.FirstName, u.LastName));
            return View(usersNames);
        }
    }
}

SklepInternetowy_v_3/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "Dostęp zabroniony";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dostęp zabroniony</h2>
<h2></h2>
<h4>Przepraszamy ale nie masz wystarczających uprawnień aby wykonąć tę akcję</h4>

SklepInternetowy_v_3/Views/Shared/_AddressPartial.cshtml
@model SklepInternetowy_v_3.Models.AddressViewModel

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HouseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HouseNumber, new { htmlAttributes = new { @class = "form-control", type="text" } })
            @Html.ValidationMessageFor(model => model.HouseNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FlatNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FlatNumber, new { htmlAttributes = new { @class = "form-control", type = "text" } })
            @Html.ValidationMessageFor(model => model.FlatNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

</div>

SklepInternetowy_v_3/Views/Shared/_Layout.cshtml
@using SklepInternetowy_v_3.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CinaMon</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CinaMon", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.IsInRole(AppConstants.AdminRole))
                {
                    @Html.Partial("~/Views/Admin/_AdminHeaderPartial.cshtml")
                }
                else
                {
                    @Html.Action("Categories", "HeaderActions")
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CinaMon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SklepInternetowy_v_3/Views/Shared/_OrdersSummary.cshtml
@using System.ComponentModel.DataAnnotations
@model IEnumerable<SklepInternetowy_v_3.Models.SubmittedOrderViewModel>

@if (Model.Any())
{
    foreach (var item in Model)
    {
        <table class="table">
            <tr>
                <th>
                    Produkty
                </th>
                <th>
                    Adres dostawy
                </th>
                <th>
                    Data złożenia
                </th>
                <th>
                    Całkowity koszt
                </th>
            </tr>
            <tr>
                <td class="col-md-5">
                    @foreach (var product in item.ItemsInOrder)
                    {
                        <div>
                            <span class="glyphicon glyphicon-ok" style="color: #5bc0de"></span>
                            @Html.DisplayFor(p => product.ProductInCart.ProductName) -
                            @Html.DisplayFor(p => product.Quantity) szt.
                        </div>
                    }
                </td>
                <td class="col-md-3">
                    <div>
                        @Html.DisplayFor(i => item.DeliveryDetails.FirstName)
                        @Html.DisplayFor(i => item.DeliveryDetails.LastName)
                    </div>
                    <div>
                        @Html.DisplayFor(i => item.DeliveryDetails.Street)
                        @Html.DisplayFor(i => item.DeliveryDetails.HouseNumber)
                        @if (item.DeliveryDetails.FlatNumber != null)
                        {
                            @:/@Html.DisplayFor(i => item.DeliveryDetails.FlatNumber)
                        }
                    </div>
                    <div>
                        @Html.DisplayFor(i => item.DeliveryDetails.ZipCode)
                        @Html.DisplayFor(i => item.DeliveryDetails.City)
                    </div>
                    <div>
                        @Html.DisplayFor(i => item.DeliveryDetails.PhoneNumber)
                    </div>
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => item.Total) PLN
                </td>
            </tr>
        </table>
    }
}
else
{
    <h1 class="empty-cart">
        Brak zrealizowanych zamówień
    </h1>
}